trainer:
  logger: true
  enable_checkpointing: true
  process_position: 0
  num_nodes: 1
  num_processes: 1
  auto_select_gpus: false
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  max_steps: -1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 50
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  num_sanity_val_steps: 2
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  amp_backend: native
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  hidden_dims: []
  pretrained: false
  encoder_kwargs: []
  fcn_kwargs: {}
data:
  batch_size: 32
  num_workers: 0
  split: 0.9
  subset: false
  dataset_kwargs: {}
